version: '3.9'

services:

  stock-exchange-emulator:
    container_name: stock-exchange-emulator
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING = postgresql://test:test@localhost:5407/stock-exchange-emulator
    build:
      context: .
      dockerfile: Src/StockExchangeEmulator.Emulator/Dockerfile

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=stock-exchange-emulator
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    command:
      - -c
      - max_prepared_transactions=100
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5407:5432"
